yml.name: TestNameFromFileProperties-yml
spring:
  datasource:
    username: admin                               # Имя администратора db
    password: qQ111111                            # Пароль администратора db
    driver-class-name: org.postgresql.Driver      # Драйвер db
    url: jdbc:postgresql://localhost:40554/pep_db # url db
  jpa:
    show-sql: true
#    properties.hibernate.format_sql: true